### ISSUE TITLE
Update Project

### ISSUE THREAD

**Issue by jasonsoohoo** [cjahner1/2023-Robot-Code#7]
- Open a new branch and commit current robot code to it.
- Once complete, create a pull request so we can "merge" into main.
- Delete dead branches while we are at this.

This will be our first practice run of using git properly. Everyone currently on the software team will participate. One person will be assigned the issue, but everyone will approve the pull request and discussion.

**Comment by sindhunaydu** [comment]
Hi, if this is open for outsiders I would like to help.

**Comment by jasonsoohoo** [comment]
This merge will be approved for the sake of maintaining our repo to current code. We will soon have to implement a style guide as well as do a more formal in-person code review.
